services:
  btp-front:
    image: mipxtx/btp.front
    ports:
      - "8080:80"
    links:
      - btp-php
    volumes:
      - ./logs/nginx:/var/log/nginx
  btp-php:
    image: mipxtx/btp.php
    links:
      - btpd
    volumes:
      - ./logs/php:/var/log/
      #- ./btp-php/src:/btp-ui
  btpd:
    image: mipxtx/btpd
    volumes:
      - ./btpd/run.sh:/btpd/run.sh
      - ./logs/btpd/:/btpd/logs/
      - ./storage:/btpd/storage
    ports:
      - 37000:37000
      - 37001:37001
      - 37002:37002
      - 37003:37003
      - 37004:37004
      - 38000:38000
      - 38000:38000/udp
      - 38001:38001
      - 38001:38001/udp
