services:
  click:
    image: yandex/clickhouse-server
    volumes:
      - ./click_data:/var/lib/clickhouse
      - ./logs/click:/var/log/clickhouse-server
      - ./clickhouse/my-config.xml:/etc/clickhouse-server/config.d/my-config.xml
      - ./clickhouse/init.sh:/docker-entrypoint-initdb.d/init.sh
    platform: linux/amd64
    ports:
      - 8123:8123
  web:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./btp-ui:/btp-ui
      - ./nginx/site.conf:/etc/nginx/conf.d/default.conf
      - ./logs/nginx:/var/log/nginx
    links:
      - php
      - click
  php:
    image: php:7-fpm
    volumes:
      - ./btp-ui:/btp-ui
      - ./logs/php:/var/log/
      - ./php/php.ini:/usr/local/etc/php/php.ini
      - ./php/docker.conf:/usr/local/etc/php-fpm.d/docker.conf
  listner:
    image: btp:listner
    volumes:
      - ./listner/src:/go/src
    ports:
      - 12345:12345
      - 12345:12345/udp
    links:
      - click
    environment:
      - "CLICK=click:8123"
      - "DUMP_TIMEOUT=5"

