services:
  btp-front:
    build: btp-front
    ports:
      - "80:80"
    links:
      - btp-php
    volumes:
      - ./logs/nginx:/var/log/nginx
  btp-php:
    image: btp:php
    links:
      - listner
    volumes:
      - ./logs/php:/var/log/
      #- ./btp-php/src:/btp-ui
  click:
    image: yandex/clickhouse-server
    volumes:
      - ./click_data:/var/lib/clickhouse
      - ./clickhouse/init.sh:/docker-entrypoint-initdb.d/init.sh
      - ./logs/click:/var/log/clickhouse-server
    ports:
      - 8123:8123
  listner:
    image: btp:listner
    ports:
      - 12345:12345
      - 12345:12345/udp
    links:
      - click
    environment:
      - "CLICK=click:8123"
      - "DUMP_TIMEOUT=15"

